In [2]:
# TENSORFLOW

import tensorflow as tf
import numpy as np

In [3]:
a=tf.constant(15)
b=tf.constant(20)

In [4]:
print(a*b)

tf.Tensor(300, shape=(), dtype=int32)


In [5]:
x=np.random.rand(100).astype(np.float32)

In [6]:
print(x)

[0.68182516 0.87208617 0.18774691 0.46451288 0.12848239 0.14692128
 0.87079114 0.33628005 0.46046335 0.42625296 0.20148166 0.03660452
 0.9506295  0.76418465 0.21761043 0.37999398 0.958878   0.512555
 0.38596722 0.47536388 0.4282201  0.863452   0.06946731 0.05002882
 0.900889   0.34457204 0.7763436  0.13641782 0.6819881  0.4240547
 0.758475   0.92565686 0.71833956 0.5602366  0.7780821  0.07972595
 0.6506808  0.96289665 0.11268034 0.24725424 0.3764271  0.5344097
 0.8528146  0.13895655 0.01483641 0.94988155 0.87403136 0.05390132
 0.17694795 0.15313563 0.89042217 0.69967604 0.85795504 0.5193077
 0.35250866 0.6258471  0.00971831 0.05341048 0.951322   0.9879326
 0.97065353 0.26298726 0.33923608 0.57778305 0.28973827 0.49859354
 0.6471938  0.9651912  0.3037276  0.65699685 0.42151016 0.5098297
 0.9101609  0.5169067  0.78244114 0.4661661  0.837714   0.76351625
 0.49749002 0.46045384 0.46561036 0.5567472  0.16684115 0.15136345
 0.5096241  0.7416573  0.02342471 0.3304677  0.30571595 0.36932623
 0

In [7]:
y=0.2*x+0.2

In [8]:
W=tf.Variable(tf.random.normal([1]))

In [9]:
b=tf.Variable(tf.zeros([1]))

In [10]:
def mse_loss():
    y_pred=W*x+b
    loss=tf.reduce_mean(tf.square(y_pred-y))
    return loss

In [11]:
optimizer=tf.optimizers.Adam()

In [12]:
for step in range(5000):
    optimizer.minimize(mse_loss, var_list=[W,b])
    if step%500==0:
        print(step, W.numpy(),b.numpy())

0 [0.01791271] [0.00099999]
500 [0.20770347] [0.19451842]
1000 [0.2043059] [0.19764437]
1500 [0.20153916] [0.19915797]
2000 [0.20036723] [0.1997991]
2500 [0.20005311] [0.19997096]
3000 [0.20000449] [0.19999751]
3500 [0.20000125] [0.19999929]
4000 [0.20000099] [0.19999944]
4500 [0.20000073] [0.19999959]


In [13]:
# KERAS
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense



dataset=pd.read_csv('diabetes.csv',delimiter=',')

In [14]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [15]:
x = dataset.iloc[:,0:8]

In [16]:
y = dataset.iloc[:,8]

In [17]:
model = Sequential()

In [18]:
model.add(Dense(12,input_shape=(8,),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221 (884.00 Byte)
Trainable params: 221 (884.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.compile(optimizer='adam',loss='binary_crossentropy' ,metrics=['accuracy'])

In [20]:
model.fit(x,y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 1ms/step - loss: 19.0996 - accuracy: 0.3607
Epoch 2/150
77/77 [==============================] - 0s 3ms/step - loss: 1.6672 - accuracy: 0.5195
Epoch 3/150
77/77 [==============================] - 0s 1ms/step - loss: 0.9584 - accuracy: 0.5417
Epoch 4/150
77/77 [==============================] - 0s 3ms/step - loss: 0.8143 - accuracy: 0.5846
Epoch 5/150
77/77 [==============================] - 0s 4ms/step - loss: 0.7202 - accuracy: 0.6042
Epoch 6/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6631 - accuracy: 0.6471
Epoch 7/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6400 - accuracy: 0.6536
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6220 - accuracy: 0.6667
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6209 - accuracy: 0.6758
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6205 - accuracy: 0.6745
Epoch 11

In [21]:
test_loss,test_accuracy=model.evaluate(x,y)
print('test_loss',test_loss)
print('test_accuracy',test_accuracy)

24/24 [==============================] - 0s 1ms/step - loss: 0.4913 - accuracy: 0.7656
test_loss 0.49130961298942566
test_accuracy 0.765625


In [54]:
# THEANO


!pip install theano

     ---------------------------------------- 2.8/2.8 MB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for theano: filename=Theano-1.0.5-py3-none-any.whl size=2668148 sha256=11b341550877dbe45ca1eef034a563fc799181cd167351426a29d3eec55effa9
  Stored in directory: c:\users\praj\appdata\local\pip\cache\wheels\2f\8b\77\45db6f8ec9086bcb5590b700fd458d4d63395433459acc3cd4
Successfully built theano


In [57]:
import theano
import theano.tensor as T
from theano import function
from theano import *
import numpy as np
import pandas as pd

In [58]:
# dscalar represent a single floating-point value 
x1=T.dscalar()
# generic scalar without specifying a specific data type.
x2=T.scalar()

In [59]:
ares=x1+x2
sres=x1-x2

In [60]:
calcares = function([x1,x2],ares)
calcsres = function([x1,x2],sres)

In [61]:
calcares(15,30)

array(45.)

In [62]:
calcsres(30,15)

array(15.)

In [63]:
x=T.dmatrix()
y=T.dmatrix()

In [65]:
z=x+y

In [66]:
f = function([x,y],z)

In [67]:
mat1 = [[10,10],[20,20]]
mat2 = [[5,5],[5,5]]

f(mat1,mat2)

array([[15., 15.],
       [25., 25.]])

In [1]:
# PYTORCH


import torch
import numpy as np

In [2]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [5]:
print(type(x_np))

<class 'torch.Tensor'>


In [6]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])


In [7]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[0.3000, 0.5007],
        [0.1355, 0.4006]])


In [14]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))

tensor([[0.2523, 0.5673, 0.6331],
        [0.0081, 0.8180, 0.0407]])
<class 'torch.Tensor'>


In [15]:
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>


In [16]:
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [17]:
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.4187, 0.8991, 0.0667, 0.9219],
        [0.0131, 0.4059, 0.2474, 0.7652],
        [0.7810, 0.3223, 0.3388, 0.7220]])


device(type='cpu')

In [19]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Device tensor is stored in ", tensor.device)

In [21]:
tensor = torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [22]:
tensor1 = torch.zeros(4,4)
print(tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [23]:
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [24]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [26]:
t = torch.ones(5)
print(t)

tensor([1., 1., 1., 1., 1.])


In [27]:
n = t.numpy()
print(n)
print(type(n))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
